version: '2'
services:
  dockergen:
    image: jwilder/docker-gen
    command: -conf /etc/docker-gen/docker-gen.conf
    container_name: dockergen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-gen-separate.conf:/etc/docker-gen/docker-gen.conf:ro
      - ./templates:/etc/docker-gen/templates:ro
      - haproxy_config:/etc/haproxy/

  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - haproxy_config:/etc/haproxy/:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

volumes:
  haproxy_config: